'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {BookOpen,NotebookPen,ChartNoAxesCombined,ArrowRight,ChevronLeft,ChevronRight,Check,RefreshCw,Shuffle,ListOrdered,List,Camera,CloudCheck,GraduationCap,ExternalLink,UserRound,LoaderCircle,TriangleAlert,Star} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import type {State,Question,Result} from '@/lib/practice';
import {api,exportBackup,importBackup} from '@/lib/local';
import {DigitalBody,DigitalOptions,DigitalExplanation,Bunny} from '@/components/digital-question';
type Meta={id:string;chapter:number;sourceNumber:string;page:number;type:string;title:string;note:string;ungraded?:boolean};
type Data={state:State;version:number;bank:Meta[];email:string;identityKind?:string};
const chapters=['全部章节','Python 基础','程序控制结构','函数与代码复用','组合数据类型','文件和数据格式化','Python 计算生态'];
const labels:Record<string,string>={choice:'单选题',multi:'多选题',blank:'填空题',disputed:'原题争议'};
function SourceImages({paths,alt}:{paths:string[];alt:string}){return <div className="source-images">{paths.map((p,i)=><a key={p} href={'.'+p} target="_blank" rel="noreferrer" title="点击放大原文图片"><img src={'.'+p} alt={`${alt}（第 ${i+1} 部分）`} /></a>)}</div>;}
export default function StudyApp(){
  const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState('home'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
  const [mode,setMode]=useState('order'),[chapter,setChapter]=useState('0'),[view,setView]=useState(0),[q,setQ]=useState<Question|null>(null),[input,setInput]=useState(''),[selected,setSelected]=useState<string[]>([]);
  const [explanation,setExplanation]=useState<{q:Question;result?:Result;advance?:boolean}|null>(null),[profile,setProfile]=useState(false),[name,setName]=useState(''),[confirmStart,setConfirmStart]=useState<{mode:string;chapter:number}|null>(null),[notice,setNotice]=useState('');
  const [syncOpen,setSyncOpen]=useState(false),[syncCode,setSyncCode]=useState(''),[joinCode,setJoinCode]=useState(''),[syncMessage,setSyncMessage]=useState(''),[syncError,setSyncError]=useState(''),[pickerOpen,setPickerOpen]=useState(false);
  const submitting=useRef(false),fileRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await api('/api/practice');setData(d);setView(d.state.session?.cursor||0);if(d.state.session&&d.state.session.cursor<d.state.session.queue.length)setTab('practice');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const s=data?.state.session,id=s?.queue[view],review=!!s&&view<s.cursor;
  useEffect(()=>{let active=true;setQ(null);setInput('');setSelected([]);if(id)api<Question>('/api/practice?question='+encodeURIComponent(id)).then(q=>{if(active)setQ(q);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id,s?.id]);
  async function mutate(payload:Record<string,unknown>){if(!data)throw Error('请先加载进度');const d=await api('/api/practice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,version:data.version})});setData(old=>old?{...old,state:d.state,version:d.version}:old);return d;}
  async function start(m:string,ch=Number(chapter)){if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{await mutate({action:'start',mode:m,chapter:['wrong','favorites'].includes(m)?0:ch});setView(0);setTab('practice');setNotice('');}catch(e){setError((e as Error).message);}finally{setBusy(false);submitting.current=false;setConfirmStart(null);}}
  function requestStart(m:string,ch=Number(chapter)){const targetChapter=['wrong','favorites'].includes(m)?0:ch;if(s&&s.cursor<s.queue.length&&s.mode===m&&s.chapter===targetChapter){setView(s.cursor);setTab('practice');setNotice('已回到上次完成的位置');return;}if(s&&s.cursor<s.queue.length)setConfirmStart({mode:m,chapter:targetChapter});else start(m,targetChapter);}
  async function answer(value:string){if(!q||!s||review||submitting.current)return;submitting.current=true;setBusy(true);setError('');try{const d=await mutate({action:'answer',sessionId:s.id,position:view,answer:value});if(q.type==='blank'||d.result.correct!==true){setExplanation({q,result:d.result,advance:true});}else{setNotice('回答正确 · 已保存到本机');setView(d.state.session!.cursor);}}catch(e){setError((e as Error).message);}finally{setBusy(false);submitting.current=false;}}
  async function toggleFavorite(questionId:string){if(!data||submitting.current)return;submitting.current=true;setBusy(true);try{await mutate({action:'favorite',questionId,value:!data.state.favorites[questionId]});}catch(e){setError((e as Error).message);}finally{submitting.current=false;setBusy(false);}}
  async function chooseQuestion(position:number){if(!data||!s)return;if(position<=s.cursor){setView(position);setPickerOpen(false);return;}if(submitting.current)return;submitting.current=true;setBusy(true);setError('');try{const d=await mutate({action:'jump',sessionId:s.id,position});setView(d.state.session!.cursor);setPickerOpen(false);setNotice('已跳到你选择的未做题目');}catch(e){setError((e as Error).message);}finally{submitting.current=false;setBusy(false);}}
  function closeExplanation(){if(explanation?.advance&&data?.state.session)setView(data.state.session.cursor);setExplanation(null);}
  async function inspect(m:Meta){setBusy(true);setError('');try{setExplanation({q:await api<Question>('/api/practice?question='+m.id)});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function saveProfile(){setBusy(true);setError('');try{await mutate({action:'profile',name});setProfile(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function upload(file?:File){if(!file||!data)return;setBusy(true);setError('');try{if(!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>8*1024*1024)throw Error('请选择小于 8MB 的 JPG、PNG 或 WebP 图片');const img=await createImageBitmap(file),canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d')!,side=Math.min(img.width,img.height);ctx.drawImage(img,(img.width-side)/2,(img.height-side)/2,side,side,0,0,256,256);img.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',.88));if(!blob)throw Error('图片处理失败');const d=await api('/api/avatar',{method:'POST',headers:{'Content-Type':'image/webp','X-State-Version':String(data.version)},body:blob});setData({...data,state:d.state,version:d.version});}catch(e){setError((e as Error).message);}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
  async function showSyncCode(){setBusy(true);setSyncError('');try{const text=await exportBackup();setSyncCode(text);const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='Python刷题备份-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setSyncMessage('备份已生成。如果微信没有下载文件，请复制下面的备份文本并妥善保存。');}catch(e){setSyncError((e as Error).message);}finally{setBusy(false);}}
  async function copySyncCode(){try{await navigator.clipboard.writeText(syncCode);setSyncMessage('已复制备份，请保存到自己的文件或笔记中。');}catch{setSyncMessage('请长按备份文本，全选后手动复制。');}}
  async function connectRecords(){setBusy(true);setSyncError('');try{await importBackup(joinCode);const d=await api('/api/practice');setData(d);setView(d.state.session?.cursor||0);setTab('home');setExplanation(null);setSyncOpen(false);setSyncCode('');setJoinCode('');setNotice('备份已恢复到本机');setError('');}catch(e){setSyncError((e as Error).message);}finally{setBusy(false);}}
  async function readBackup(file?:File){if(!file)return;setSyncError('');try{if(file.size>4*1024*1024)throw Error('备份文件过大，请选择本系统导出的 JSON 文件');const text=await file.text();setJoinCode(text);}catch(e){setSyncError((e as Error).message);}}
  const state=data?.state,favoriteCount=Object.keys(data?.state.favorites||{}).length,wrongCount=Object.keys(state?.wrong||{}).length,accuracy=state?.total?Math.round(state.correct/state.total*100):null;
  const avatar=<span className="avatar">{state?.avatar?<img src={state.avatar} alt="个人头像"/>:<UserRound size={25}/>}</span>;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="./"><Bunny small/><span>Python 刷题<small>计算机二级 · 阿福课堂题库</small></span></a><div className="nav-caption">我的学习空间</div><nav>{[{id:'home',label:'学习概览',icon:ChartNoAxesCombined},{id:'practice',label:'开始刷题',icon:BookOpen},{id:'wrong',label:'我的错题本',icon:NotebookPen},{id:'favorites',label:'我的收藏',icon:Star}].map(n=><button key={n.id} className={'nav-item '+(tab===n.id?'active':'')} onClick={()=>{setTab(n.id);setNotice('');}}><n.icon size={20}/>{n.label}{n.id==='wrong'&&wrongCount>0&&<span className="badge-count">{wrongCount}</span>}</button>)}</nav><div className="sidebar-note"><GraduationCap size={25}/><b>每一次练习，都算数。</b><p>做错的题再练三次，<br/>把知识真正记住。</p><a href="./source.pdf" target="_blank" rel="noreferrer">查看原始题库 <ExternalLink size={13}/></a></div><div className="sidebar-bottom"><span className="green-dot"/>免登录练习 · 进度自动保存</div></aside>
  <main className="main"><header className="topbar"><span className="breadcrumb">学习空间 <span>/</span> {tab==='home'?'学习概览':tab==='wrong'?'错题本':tab==='favorites'?'我的收藏':'刷题练习'}</span><div className="top-actions"><button className="icon-btn" onClick={load} disabled={busy||loading} aria-label="重新读取本机进度"><RefreshCw size={17} className={loading?'spin':''}/></button><button aria-label="修改个人信息" className="profile-button" onClick={()=>{setName(state?.name||'');setProfile(true);}}>{avatar}<span>{state?.name||'我的账户'}</span></button></div></header>
  {error&&<div className="error" role="alert"><TriangleAlert size={18}/><span>{error}</span><button onClick={load}>重新读取</button></div>}
  {loading&&!data?<div className="loading"><LoaderCircle className="spin"/>正在读取学习进度…</div>:!data?<div className="empty"><CloudCheck/><h2>加载你的学习空间</h2><p>无需登录。读取本机记录后，即可开始练习。</p><button className="primary" onClick={load}>重新读取</button></div>:<>
  {tab==='home'&&<><section className="page-heading"><div><div className="eyebrow">✦ 小兔陪你，一起过级 ✦</div><h1>你好，{state!.name}<span className="hello-dot">.</span></h1><p>从一道题开始，继续今天的 Python 练习。</p></div><button className="sync-pill" onClick={()=>setSyncOpen(true)}><CloudCheck size={15}/> 保存与备份</button></section><section className="stats-grid"><div className="stat-card"><span>累计作答</span><strong>{state!.total}<small>次</small></strong><p>已练习 {Object.keys(state!.seen).length} 道不同的题</p><BookOpen className="stat-icon"/></div><div className="stat-card"><span>答题正确率</span><strong>{accuracy??'—'}<small>{accuracy===null?'':'%'}</small></strong><p>{state!.correct} 次正确 / {state!.total} 次有效作答</p><ChartNoAxesCombined className="stat-icon"/></div><div className="stat-card"><span>待巩固错题</span><strong>{wrongCount}<small>道</small></strong><p>同一道题连续答对 3 次后移出</p><NotebookPen className="stat-icon"/></div></section>
  <section className="home-columns"><div className="practice-panel"><div className="section-label"><span className="square-icon"><BookOpen size={21}/></span><div><h2>开启一轮练习</h2><p>按自己的节奏，逐题掌握知识点</p></div></div><label className="field-label">练习方式</label><Tabs value={mode} onValueChange={setMode}><TabsList className="mode-tabs"><TabsTrigger value="order"><ListOrdered/>顺序刷题</TabsTrigger><TabsTrigger value="random"><Shuffle/>随机刷题</TabsTrigger></TabsList></Tabs><label className="field-label">选择章节</label><Select value={chapter} onValueChange={setChapter}><SelectTrigger className="chapter-select"><SelectValue/></SelectTrigger><SelectContent>{chapters.map((c,i)=><SelectItem key={c} value={String(i)}>{c} · {data.bank.filter(q=>!i||q.chapter===i).length} 题</SelectItem>)}</SelectContent></Select><button className="primary start-button" disabled={busy} onClick={()=>requestStart(mode)}>{s&&s.cursor<s.queue.length&&s.mode===mode&&s.chapter===Number(chapter)?'继续上次':'开始'}{mode==='random'?'随机':'顺序'}刷题 <ArrowRight size={18}/></button>{s&&s.cursor<s.queue.length&&<button className="resume" onClick={()=>{setView(s.cursor);setTab('practice');}}>继续上次练习 <span>已完成 {s.cursor} / {s.queue.length} 题 →</span></button>}</div><div className="notebook-promo"><Bunny/><h2>每天一点，进步一点。</h2><p>答错自动收录，再次答错重新计数。<br/>在不同轮次中连续答对三次，<br/>才算真正过关。</p><div className="three-steps"><span>1<Check/></span><i/><span>2<Check/></span><i/><span>3<Check/></span></div><button disabled={busy||!wrongCount} onClick={()=>requestStart('wrong')}>{wrongCount?'复习 '+wrongCount+' 道错题':'还没有错题，开始练习吧'}<ArrowRight size={17}/></button></div></section>
  <section className="chapters-panel"><div className="section-title"><h2>题库章节</h2><span>原文收录 · 共 483 题</span></div><div className="chapter-grid">{chapters.slice(1).map((c,i)=>{const list=data.bank.filter(q=>q.chapter===i+1),done=list.filter(q=>state!.seen[q.id]).length;return <button key={c} onClick={()=>start('unseen',i+1)} className="chapter-card" title={'从未学习题目开始：'+c}><span className="chapter-num">0{i+1}</span><div><h3>{c}</h3><p>{done} / {list.length} 题已练习</p><Progress value={done/list.length*100}/></div><ChevronRight size={17}/></button>;})}</div></section><p className="source-note">来源：《阿福课堂二级 Python 理论题部分》 · 保留原题编号及修改题，共 483 条。3 道缺陷题不计分。回看题目不影响正确率。</p></>}
  {tab==='practice'&&<><section className="page-heading compact"><div><div className="eyebrow">专注当下这一题</div><h1>刷题练习</h1></div><div className="practice-actions"><button className="secondary" disabled={!s||!s.queue.length} onClick={()=>setPickerOpen(true)}><List size={16}/>题目列表</button><div className="practice-actions"><button className="secondary" disabled={!s||!s.queue.length} onClick={()=>setPickerOpen(true)}><List size={16}/>题目列表</button><button className="secondary" onClick={()=>setTab('home')}>练习设置</button></div></div></section>{!s?<div className="empty"><BookOpen/><h2>准备好开始了吗？</h2><p>选择章节和练习方式，开始第一道题。</p><button className="primary" onClick={()=>setTab('home')}>选择练习</button></div>:<><div className="session-bar"><span>{s.mode==='random'?'随机刷题':s.mode==='wrong'?'错题复习':s.mode==='favorites'?'收藏练习':s.mode==='unseen'?'未学题目':'顺序刷题'}<i>·</i>{chapters[s.chapter]}</span><b>{s.cursor} / {s.queue.length} 已完成</b></div><Progress value={s.queue.length?s.cursor/s.queue.length*100:0}/>{view>=s.queue.length?<div className="empty finished"><span className="finish-icon"><Check size={38}/></span><h2>{s.queue.length?'这一轮，完成了！':'暂时没有需要复习的错题'}</h2><p>{s.queue.length?`本轮有效作答 ${s.history.filter(r=>r.correct!==null).length} 题，答对 ${s.history.filter(r=>r.correct).length} 题。`:'继续练习，答错的题会自动加入这里。'}</p><div className="row-actions"><button className="secondary" onClick={()=>setTab('home')}>返回学习概览</button>{wrongCount>0&&<button className="primary" disabled={busy} onClick={()=>start('wrong')}>再练一轮错题</button>}</div>{s.queue.length>0&&<button className="text-button" onClick={()=>setView(s.queue.length-1)}>回看上一题</button>}</div>:!q?<div className="loading"><LoaderCircle className="spin"/>正在载入原题…</div>:<article className="question-card" key={q.id}><div className="question-top"><div className="question-badges"><span className="type-badge">{labels[q.type]}</span><span>{chapters[q.chapter]} · 原题 {q.sourceNumber}</span></div><span className="question-count">{view+1}<small> / {s.queue.length}</small></span></div>{q.note&&<p className="question-note"><TriangleAlert size={16}/>{q.note}</p>}<div className="question-tools"><span>点击选项即可作答</span><button className={'favorite-button '+(state!.favorites[q.id]?'saved':'')} disabled={busy} aria-pressed={!!state!.favorites[q.id]} onClick={()=>toggleFavorite(q.id)}><Star size={18} fill={state!.favorites[q.id]?'currentColor':'none'}/>{state!.favorites[q.id]?'已收藏':'收藏本题'}</button></div><DigitalBody id={q.id}/>{review&&<DigitalOptions id={q.id} disabled result={{...s.history[view],canonical:q.canonical}}/>}
  {review?<div className="review-panel"><div className="review-status"><span>{s.history[view]?.correct===null?'本题不计分':s.history[view]?.correct?'✓ 已答对':'已加入错题本'}</span><span>你的答案：{s.history[view]?.answer||'未作答'}</span></div><h3>原书答案与解析</h3><DigitalExplanation id={q.id}/></div>:<div className="answer-area"><p>{q.ungraded?'本题保留原文供学习，不计入正确率。':q.type==='multi'?'选择全部正确选项，再提交答案。':q.type==='choice'?'点击选项提交，答对自动进入下一题。':'输入答案，提交后查看原书解析。'}</p>{q.type==='choice'?<DigitalOptions id={q.id} disabled={busy} onChoose={answer}/>:q.type==='multi'?<><DigitalOptions id={q.id} selected={selected} disabled={busy} onChoose={a=>setSelected(old=>old.includes(a)?old.filter(x=>x!==a):[...old,a])}/><button className="primary" disabled={busy||!selected.length} onClick={()=>answer(selected.sort().join(''))}>提交答案</button></>:q.type==='blank'?<form onSubmit={e=>{e.preventDefault();answer(input);}}><label className="sr-only" htmlFor="answer-input">填写答案</label><input id="answer-input" className="answer-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="在这里填写答案" autoComplete="off" maxLength={1000}/><button className="primary" disabled={busy||(!input.trim()&&!q.ungraded)}>提交并查看解析</button></form>:<button className="primary" disabled={busy} onClick={()=>answer('')}>查看原书说明并继续</button>}</div>}
  <details className="original-toggle"><summary>对照 PDF 原题</summary><SourceImages paths={review?q.originalImages:q.images} alt="PDF 原题"/></details><footer className="question-footer"><button className="secondary" disabled={busy||view===0} onClick={()=>setView(view-1)}><ChevronLeft size={16}/>上一题</button><a href={'./source.pdf#page='+q.page} target="_blank" rel="noreferrer">PDF 第 {q.page} 页 <ExternalLink size={13}/></a>{review?<button className="primary" onClick={()=>setView(view+1)}>{view+1===s.cursor?'继续作答':'下一题'}<ChevronRight size={16}/></button>:<span className="subtle">{busy?'正在保存…':'作答后自动保存'}</span>}</footer></article>}<div className="practice-bottom"><span><CloudCheck size={15}/>{notice||'进度与错题自动保存，回看不重复计分。'}</span><button className="text-button" onClick={()=>setTab('wrong')}>查看错题本 →</button></div></>}</>}
  {tab==='wrong'&&<><section className="page-heading"><div><div className="eyebrow">温故，而知新</div><h1>我的错题本 <small>{wrongCount}</small></h1><p>连续答对 3 次移出错题本；再次答错，连续次数归零。</p></div><button className="primary" disabled={!wrongCount||busy} onClick={()=>requestStart('wrong')}>开始复习 <ArrowRight size={17}/></button></section><div className="wrong-list">{wrongCount===0?<div className="empty"><NotebookPen/><h2>错题本还是空的</h2><p>继续刷题吧，需要巩固的题目会自动出现在这里。</p><button className="secondary" onClick={()=>setTab('home')}>去刷题</button></div>:data.bank.filter(q=>state!.wrong[q.id]).map(m=><button className="wrong-row" key={m.id} disabled={busy} onClick={()=>inspect(m)}><span className="type-badge">{labels[m.type]}</span><div className="wrong-title"><h3>{m.title}</h3><p>{chapters[m.chapter]} · PDF 第 {m.page} 页 · 累计答错 {state!.wrong[m.id].count} 次</p></div><span className="streak">{[0,1,2].map(n=><i key={n} className={n<state!.wrong[m.id].streak?'done':''}/>)}<small>连续 {state!.wrong[m.id].streak}/3</small></span><ChevronRight size={18}/></button>)}</div><p className="source-note">点击题目可查看原文解析，不计作答次数。点击「开始复习」才会更新连续答对次数。</p></>}
  {tab==='favorites'&&<><section className="page-heading"><div><div className="eyebrow">✦ 收藏值得再看一遍的题 ✦</div><h1>我的收藏 <small>{favoriteCount}</small></h1><p>喜欢的题、重要的知识点，放进自己的小口袋。</p></div><button className="primary" disabled={!favoriteCount||busy} onClick={()=>requestStart('favorites')}>练习收藏 <ArrowRight size={17}/></button></section><div className="wrong-list">{favoriteCount===0?<div className="empty"><Bunny/><h2>收藏夹等你装满</h2><p>在题目或解析旁点击星星，就能收藏。</p><button className="secondary" onClick={()=>setTab('home')}>去挑一道题</button></div>:data.bank.filter(m=>state!.favorites[m.id]).map(m=><div className="favorite-row" key={m.id}><button className="favorite-view" onClick={()=>inspect(m)} disabled={busy}><Star size={20}/><div><h3>{m.title.split('\n')[0]}</h3><p>{chapters[m.chapter]} · 原题 {m.sourceNumber}</p></div><ChevronRight size={18}/></button><button className="text-button" disabled={busy} onClick={()=>toggleFavorite(m.id)} aria-label={'取消收藏 '+m.id}>取消收藏</button></div>)}</div></>}
  </>}</main>
  <Dialog open={!!explanation} onOpenChange={open=>{if(!open)closeExplanation();}}><DialogContent className="explanation-dialog sm:max-w-3xl"><DialogHeader><DialogTitle>{explanation?.result?explanation.result.correct===null?'原题说明':explanation.result.correct?'回答正确':'再巩固一下这道题':'原书答案与解析'}</DialogTitle><DialogDescription>{explanation?.result?.correct===false?'已加入错题本，连续答对三次后移出。':'以下内容直接来自 PDF 原文。'}</DialogDescription></DialogHeader><div className="explanation-scroll">{explanation&&<>{!explanation.advance&&<><DigitalBody id={explanation.q.id}/><DigitalOptions id={explanation.q.id} disabled/></>}{explanation.result&&<p className="submitted-answer">你的答案：{explanation.result.answer||'未作答'}</p>}{explanation.q.note&&<p className="question-note">{explanation.q.note}</p>}<DigitalExplanation id={explanation.q.id}/><button className="favorite-button" disabled={busy} onClick={()=>toggleFavorite(explanation.q.id)}><Star size={17} fill={state?.favorites[explanation.q.id]?'currentColor':'none'}/>{state?.favorites[explanation.q.id]?'已收藏':'收藏本题'}</button><details className="original-toggle"><summary>对照 PDF 原解析</summary><SourceImages paths={explanation.q.analysisImages} alt="原书答案与解析"/></details><a className="text-button" href={'./source.pdf#page='+explanation.q.page} target="_blank" rel="noreferrer">查看 PDF 原页 ↗</a></>}</div><button className="primary" onClick={closeExplanation}>{explanation?.advance?'看懂了，继续下一题':'关闭解析'}<ArrowRight size={17}/></button></DialogContent></Dialog>
  <Dialog open={profile} onOpenChange={setProfile}><DialogContent><DialogHeader><DialogTitle>个人信息</DialogTitle><DialogDescription>免登录也能保存头像、昵称和学习记录。</DialogDescription></DialogHeader><div className="profile-edit"><button className="avatar-upload" disabled={busy} onClick={()=>fileRef.current?.click()} aria-label="修改头像">{avatar}<span><Camera size={16}/></span></button><button className="text-button" disabled={busy} onClick={()=>fileRef.current?.click()}>更换头像</button><input type="file" hidden ref={fileRef} accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></div><label className="field-label" htmlFor="nickname">昵称</label><input id="nickname" className="answer-input" value={name} onChange={e=>setName(e.target.value)} maxLength={40}/><p className="account-email">{data?.email?"原登录账户："+data.email:"本机保存 · 换设备或清理缓存前请导出备份"}</p><button className="secondary" onClick={()=>{setProfile(false);setSyncOpen(true);}}>导出 / 导入备份</button>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy||!name.trim()} onClick={saveProfile}>{busy?'正在保存…':'保存个人信息'}</button></DialogContent></Dialog>
  <Dialog open={pickerOpen} onOpenChange={setPickerOpen}><DialogContent className="picker-dialog"><DialogHeader><DialogTitle>选择题目</DialogTitle><DialogDescription>已做题可以回看；未做题会移动到当前作答位置。</DialogDescription></DialogHeader><div className="question-picker-grid">{s?.queue.map((qid,i)=>{const meta=data?.bank.find(m=>m.id===qid),done=i<s.cursor,current=i===s.cursor;return <button key={qid} className={'picker-item '+(done?'done ':'')+(current?'current':'')} onClick={()=>chooseQuestion(i)} aria-label={'第 '+(i+1)+' 题'}><strong>{i+1}</strong><span>{current?'正在做':done?'已做过':'未做'}</span><small>{meta?.title?.split('\n')[0]||'题目'}</small></button>;})}</div></DialogContent></Dialog>
  <Dialog open={syncOpen} onOpenChange={open=>{setSyncOpen(open);if(!open){setSyncCode('');setSyncMessage('');setSyncError('');}}}><DialogContent className="sync-dialog"><DialogHeader><DialogTitle>保存与备份</DialogTitle><DialogDescription>每次作答会自动保存到当前设备。正常关闭、重开不会清空。不同浏览器和设备的记录各自独立；清理缓存前请导出备份。</DialogDescription></DialogHeader><section className="sync-section"><h3>① 导出当前学习记录</h3><p>备份包括进度、错题、收藏、连续答对次数、昵称和头像。可在另一台设备导入；不会自动同步。</p><button className="secondary" disabled={busy} onClick={showSyncCode}>导出备份文件</button>{syncCode&&<><label className="field-label" htmlFor="backup-text">备份文本（下载不方便时可复制）</label><textarea id="backup-text" className="sync-code" readOnly value={syncCode} onFocus={e=>e.target.select()}/><button className="secondary" onClick={copySyncCode}>复制备份文本</button></>}</section><section className="sync-section"><h3>② 恢复已有备份</h3><p>导入将替换这台设备的当前记录，不会合并。请先导出当前记录。</p><label className="field-label" htmlFor="backup-file">选择备份文件</label><input id="backup-file" type="file" accept=".json,application/json" onChange={e=>readBackup(e.target.files?.[0])}/><label className="field-label" htmlFor="import-text">或粘贴备份文本</label><textarea id="import-text" className="answer-input" value={joinCode} onChange={e=>setJoinCode(e.target.value)} placeholder="粘贴本系统导出的完整备份文本" maxLength={4*1024*1024} autoComplete="off" spellCheck={false}/><button className="primary" disabled={busy||!joinCode.trim()} onClick={connectRecords}>确认替换并恢复备份</button></section>{syncError&&<p className="form-error" role="alert">{syncError}</p>}{syncMessage&&<p className="sync-message" role="status">{syncMessage}</p>}</DialogContent></Dialog>
  <Dialog open={!!confirmStart} onOpenChange={open=>{if(!open)setConfirmStart(null);}}><DialogContent><DialogHeader><DialogTitle>开启新一轮练习？</DialogTitle><DialogDescription>本轮尚有未完成题目。累计正确率和错题本会保留，本轮未完成进度将被替换。</DialogDescription></DialogHeader><div className="row-actions"><button className="secondary" onClick={()=>setConfirmStart(null)}>保留本轮</button><button className="primary" disabled={busy} onClick={()=>confirmStart&&start(confirmStart.mode,confirmStart.chapter)}>开启新一轮</button></div></DialogContent></Dialog>
  </div>;
}







